on:
  push: # O workflow ser치 executado em um push
    branches:
      - develop # Especifica que o workflow ser치 disparado apenas para o branch 'develop'
# Nome do workflow
name: 游 Deploy website on push

# Defini칞칚o dos jobs do workflow
jobs:
  web-deploy:
    name: 游꿀 Deploy # Nome do job
    runs-on: ubuntu-latest # Define o sistema operacional que ser치 usado para executar o job

    # Lista de etapas (steps) a serem executadas
    steps:
      - name: 游뚴 Get latest code # Nome da etapa
        uses: actions/checkout@v4 # Usa a a칞칚o oficial de checkout para obter o c칩digo mais recente do reposit칩rio

      - name: 游늭 Sync files # Nome da etapa
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5 # Usa a a칞칚o FTP-Deploy-Action para sincronizar arquivos via FTP
        with:
          server: ${{ secrets.ftp_host }} # O endere칞o do servidor FTP 칠 fornecido a partir dos segredos do reposit칩rio
          username: ${{ secrets.ftp_user }} # Nome de usu치rio do FTP fornecido a partir dos segredos do reposit칩rio
          password: ${{ secrets.ftp_pass }} # Senha do FTP fornecida a partir dos segredos do reposit칩rio
          server-dir: public_html/_api/silab_v1/_devTest/ # Diret칩rio no servidor onde os arquivos ser칚o enviados, deve terminar com '/'
